// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBx-Iq7RMrwAtk8hK-j0BnmfLmJRu_kHNI',
    appId: '1:478231720986:web:12fe79d5f4acc09a2e0da3',
    messagingSenderId: '478231720986',
    projectId: 'cashere-42b21',
    authDomain: 'cashere-42b21.firebaseapp.com',
    storageBucket: 'cashere-42b21.firebasestorage.app',
    measurementId: 'G-FZB540H4JG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjLEAxrgeWXu5ECZhz2UPogT8kprwQ1tQ',
    appId: '1:478231720986:android:62338816874683b72e0da3',
    messagingSenderId: '478231720986',
    projectId: 'cashere-42b21',
    storageBucket: 'cashere-42b21.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAf-tYlj6tf48y5ShY9t9G1o6TaFRILnlY',
    appId: '1:478231720986:ios:41c97a2abde30d502e0da3',
    messagingSenderId: '478231720986',
    projectId: 'cashere-42b21',
    storageBucket: 'cashere-42b21.firebasestorage.app',
    iosBundleId: 'com.example.kasirBuburAyam72',
  );
  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAf-tYlj6tf48y5ShY9t9G1o6TaFRILnlY',
    appId: '1:478231720986:ios:41c97a2abde30d502e0da3',
    messagingSenderId: '478231720986',
    projectId: 'cashere-42b21',
    storageBucket: 'cashere-42b21.firebasestorage.app',
    iosBundleId: 'com.example.kasirBuburAyam72',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBx-Iq7RMrwAtk8hK-j0BnmfLmJRu_kHNI',
    appId: '1:478231720986:web:a3cfce4edb18b5462e0da3',
    messagingSenderId: '478231720986',
    projectId: 'cashere-42b21',
    authDomain: 'cashere-42b21.firebaseapp.com',
    storageBucket: 'cashere-42b21.firebasestorage.app',
    measurementId: 'G-5PZEQQ5DV7',
  );
}
